import 'strings.dart';

const Map<String, String> languageEn = {
  Ids.educationalLiterature: 'Educational literature',
  Ids.catalogue: 'Catalogue',
  Ids.auto: 'AUTO',
  Ids.reading: 'READING',
  Ids.control: 'CONTROL',
  Ids.contents: 'CONTENTS',
  Ids.swipe: 'Swipe',
  Ids.leaf: 'Leaf',
  Ids.scroll: 'Scroll',
  Ids.tap: 'Tap',
  Ids.flippingTheVolumeButton: 'Flipping the volume button',
  Ids.books: 'Books',
  Ids.bookshelf: 'Bookshelf',
  Ids.english: 'ENGLISH',
  Ids.saveAsNote: 'SAVE AS NOTE',
  Ids.tooSmallFontIsNotGoodForProtectingYourEyes: 'Too small font is not good for protecting your eyes!',
  Ids.sirTheFontHasReachedItsMaximumValue: 'Sir, the font has reached its maximum value!',
  Ids.finish: 'finish',
  Ids.font: 'font',
  Ids.importFont: 'import font',
  Ids.confirm: 'Confirm',
  Ids.addBooks: 'Add books',
  Ids.ignore: 'Ignore',
  Ids.detectedTextDes: 'Detected that the text is too long, try chapter segmentation?',
  Ids.chapterIsBeingSplit: 'Chapter is being split ...',
  Ids.confirmSplitChapter: 'Confirm that chapter splitting is required',
  Ids.innerSetting: 'Setting',
  Ids.boldStyle: 'Bold',
  Ids.italicStyle: 'Italic',
  Ids.underscore: 'UnderScore',
  Ids.strikeThrough: 'StrikeThrough',
  Ids.fontColorStyle: 'Font Color',
  Ids.insertLink: 'Insert Link',
  Ids.insertImage: 'Insert Image',
  Ids.insertCaret: 'Insert Caret',
  Ids.pleaseEnterTheLink: 'Please enter the link',
  Ids.pleaseEnterLinkDescription: 'Please enter a link description',
  Ids.pleaseSelectImage: 'Please select an image',
  Ids.splitScreen: 'Split Screen',
  Ids.justShow: 'Just show',
  Ids.edit: 'Edit',
  Ids.insertDelimiter: 'Insert Delimiter',
	Ids.keep:'keep',
	Ids.saveAs:'Save as',
	Ids.pleaseSelectAnOutputFile:'Please select an output file:',
};
