import 'strings.dart';

const Map<String, String> languageZhHans = {
  Ids.tooSmallFontIsNotGoodForProtectingYourEyes: '字体过小不利于保护您的眼睛!',
  Ids.sirTheFontHasReachedItsMaximumValue: '客官，字体已经达到最大值！',
  Ids.importFont: '导入字体',
  Ids.confirm: '确认',
  Ids.boldStyle: '粗体',
  Ids.italicStyle: '斜体',
  Ids.underscore: '下划线',
  Ids.strikeThrough: '删除线',
  Ids.fontColorStyle: '字体颜色',
  Ids.insertLink: '插入链接',
  Ids.insertImage: '插入图片',
  Ids.insertCaret: '插入符号',
  Ids.pleaseEnterTheLink: '请输入链接',
  Ids.pleaseEnterLinkDescription: '请输入链接描述',
  Ids.pleaseSelectImage: '请选择图片',
  Ids.splitScreen: '分屏',
  Ids.justShow: '只看',
  Ids.edit: '编辑',
  Ids.insertDelimiter: '插入分隔符',
  Ids.keep: '保存',
  Ids.saveAs: '另存为',
  Ids.pleaseSelectAnOutputFile: '请选择一个输出文件：',
  Ids.newline: '换行',
  Ids.newFile: '新文件',
  Ids.openFile: '打开文件',
  Ids.pleaseSelectTheRequiredMarkdownFile: '请选择需要的Markdown文件',
  Ids.welcomeToFlutterMarkdownEditor: '欢迎使用Flutter Markdown Editor',
};
