import 'strings.dart';

const Map<String, String> languageZhHant = {
  Ids.tooSmallFontIsNotGoodForProtectingYourEyes: '字體過小不利於保護您的眼睛!',
  Ids.sirTheFontHasReachedItsMaximumValue: '客官，字體已經達到最大值！ ',
  Ids.importFont: '導入字體',
  Ids.confirm: '確認',
  Ids.boldStyle: '粗體',
  Ids.italicStyle: '斜體',
  Ids.underscore: '下劃線',
  Ids.strikeThrough: '刪除線',
  Ids.fontColorStyle: '字體顏色',
  Ids.insertLink: '插入鏈接',
  Ids.insertImage: '插入圖片',
  Ids.insertCaret: '插入符號',
  Ids.pleaseEnterTheLink: '請輸入鏈接',
  Ids.pleaseEnterLinkDescription: '請輸入鏈接描述',
  Ids.pleaseSelectImage: '請選擇圖片',
  Ids.splitScreen: '分屏',
  Ids.justShow: '只看',
  Ids.edit: '編輯',
  Ids.insertDelimiter: '插入分隔符',
  Ids.keep: '保持',
  Ids.saveAs: '另存為',
  Ids.pleaseSelectAnOutputFile: '請選擇一個輸出文件：',
	Ids.newline:'換行',
	Ids.newFile:'新文件',
	Ids.openFile:'打開文件',
	Ids.pleaseSelectTheRequiredMarkdownFile:'請選擇需要的Markdown文件',
	Ids.welcomeToFlutterMarkdownEditor:'歡迎使用Flutter Markdown Editor',
};
