import 'strings.dart';

const Map<String, String> languageEn = {
  Ids.tooSmallFontIsNotGoodForProtectingYourEyes: 'Too small font is not good for protecting your eyes!',
  Ids.sirTheFontHasReachedItsMaximumValue: 'Sir, the font has reached its maximum value!',
  Ids.importFont: 'import font',
  Ids.confirm: 'Confirm',
  Ids.boldStyle: 'Bold',
  Ids.italicStyle: 'Italic',
  Ids.underscore: 'UnderScore',
  Ids.strikeThrough: 'StrikeThrough',
  Ids.fontColorStyle: 'Font Color',
  Ids.insertLink: 'Insert Link',
  Ids.insertImage: 'Insert Image',
  Ids.insertCaret: 'Insert Caret',
  Ids.pleaseEnterTheLink: 'Please enter the link',
  Ids.pleaseEnterLinkDescription: 'Please enter a link description',
  Ids.pleaseSelectImage: 'Please select an image',
  Ids.splitScreen: 'Split Screen',
  Ids.justShow: 'Just show',
  Ids.edit: 'Edit',
  Ids.insertDelimiter: 'Insert Delimiter',
  Ids.keep: 'keep',
  Ids.saveAs: 'Save as',
  Ids.pleaseSelectAnOutputFile: 'Please select an output file:',
  Ids.newline: 'newline',
  Ids.newFile: 'new file',
  Ids.openFile: 'Open File',
  Ids.pleaseSelectTheRequiredMarkdownFile: 'Please select the required Markdown file',
  Ids.welcomeToFlutterMarkdownEditor: 'Welcome to Flutter Markdown Editor',
};
